### ISSUE TITLE
Documentation site is broken

### ISSUE THREAD

**Issue by k2snowman69** [snowcoders/sortier-documentation#57]
Going to https://snowcoders.github.io/sortier/#/configuration seems to render an empty page...

**Comment by k2snowman69** [comment]
Looks like it was an issue with Github and CORS but seems to have been resolved now. Not sure what was going on there but I'll give it a try again tomorrow and make sure :-)

**Comment by kamranayub** [comment]
I just tried on my phone and am still getting a blank page, it should be a new session since I only visited on desktop

**Comment by k2snowman69** [comment]
Well in that case let me package all dependencies in the output for now and we can root cause it later :-). Give me a few minutes here...

**Comment by kamranayub** [comment]
Yup working fine now! 👏

**Comment by k2snowman69** [comment]
Well that makes no sense but okay... If you look in the [docs/index.html](https://github.com/snowcoders/sortier/blob/master/docs/index.html) I'm still actually referencing unpkg but no longer getting a CORS issue... 

Found the associated task... Looks like several people are running into this due to unpkg migrating some of their content
https://github.com/unpkg/unpkg.com/issues/176

I'll revert the changes I've made whenever that migration completes :-)

**Comment by k2snowman69** [comment]
Closing this out as it's working now but will need to undo the CORS issues after that gets resolved in unpkg. Tracking with 
https://github.com/snowcoders/sortier-documentation/issues/62
